# First couple cells shows the current directory list

In [ ]:
!tree

In [43]:
#http://sebsauvage.net/python/snyppets/

import os
for filename in os.listdir(r'./'):
    print filename

ContextFreeGrammar.java
ALL-WORKING -SQLITE_and_MYSQL.ipynb
testfile.txt
.git
.ipynb_checkpoints
context-free
eqns.txt
Context-Free.ipynb
nltk_test.txt
Nltktest
data

# BELOW - - - - -   ALL WORKING WELL

# Create Sqlite database

In [223]:
import sqlite3
conn = sqlite3.connect('data/sqlite-01.db')

# Creating Sqlite Tables

In [3]:
delete the database
# !rm data/sqlite-01.db

# Create Sqlite Tables

In [72]:
import sqlite3
conn = sqlite3.connect('data/sqlite-01.db')

c = conn.cursor()

# Create table, both fields 'code' and 'keyword' in this case are text.
c.execute('''CREATE TABLE python
             (code text, keyword text)''')

# Save (commit) the changes
conn.commit()

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.

conn.close()

ERROR:root:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 38))

OperationalError: table python already exists

In [83]:
%%HTML
<h1> Notice above the ' conn.close() '</html><br />
<span style="color:red">Be sure to close the database. VERY Important </span>'))

In [6]:
#https://sqlite.org/pragma.html
# verify database integrity
!sqlite3 data/sqlite-01.db "pragma integrity_check;"

ok

# WORKING FINE

In [3]:
import sqlite3
import base64
conn = sqlite3.connect('data/sqlite-01.db')
c = conn.cursor()
# Larger example that inserts many records at a time

a = encodedlistvalue=base64.b64encode(
    """
∈ means '(is) an element of'

For instance, 'Let a ∈ A
' means 'Let a be an element of A'
""")
#a = 'xxccccccccccxxxxxxx'
b = 'what is'

#c.execute("INSERT INTO python VALUES (?, ?)" a, b)
#c.execute("INSERT INTO python VALUES (%s, %s,)", (a, b))
c.execute("INSERT INTO python VALUES (?,?)", (a,b))

conn.commit()
conn.close()

# Reading unconverted base64 data

In [65]:
import sqlite3
conn = sqlite3.connect('data/sqlite-01.db')
c = conn.cursor()# Never 
for row in c.execute('SELECT * FROM python ORDER BY code'):
        print(row),"\n-----\n"
conn.commit()
conn.close()

(u'CnN0YXJ0c2hhcGUgUElVTUEKYmFja2dyb3VuZCB7IGIgLS44IHNhdCAxICBoIC0xMH0gCnJ1bGUgUElVTUEgewoyMDAgKiB7eSAuMSBzIC45OTc1IHIgLS4xfSAgRUxFIHtzIC4wNH0KMTAwICoge3kgLS4xIHMgLjk5MyByIC4yfSAgRUxFIHtzIC4wNH0KfQpydWxlIEVMRSB7CkVMIHt4IDEuNiAgciA5MCB9CkVMIHt4ICAtMS42ICByIDkwIGZsaXAgMTgwIH0KfQpydWxlIEVMewpQRU57fQpFTHtzIC45OTkgciAtLjEwMyB4IC4yfQp9CnJ1bGUgRUwgMC4wMDAyNTEgewpFTHtmbGlwIDE4MH0KfQpydWxlIEVMIDAuMDAyIHsKRUwye3MgLjh9Ci8vRUwye2ZsaXAgMCBzIC44fQp9CnJ1bGUgRUwyewpQRU57fQpFTDJ7cyAuOTk5NiByIC0uMDgzODEgeCAuMn0KfQpydWxlIEVMMiAwLjAwMDI1MSB7CkVMMntmbGlwIDE4MH0KfQpydWxlIFBFTiAzIHsKUEVOTkEge2IgMX0KfQpydWxlIFBFTnsKLy9QRU5OQSB7YiAtMSB6IC0xMH0KfQpydWxlIFBFTk5BewpDSVJDTEV7YSAtLjk5IHMgMzUgYiAtMSB6IC0yfQovL0NJUkNMRXthIC0uOTk4IHMgMTAgIHogLTF9CkNJUkNMRXthIC0uN30KfSAgICAKCg==', u'PIUMA.cfdg')
-----

#### convert the data with exterior decoder
### Not convenient, but good for checking data

In [14]:
a = base64.decodestring('CnN0YXJ0c2hhcGUgUElVTUEKYmFja2dyb3VuZCB7IGIgLS44IHNhdCAxICBoIC0xMH0gCnJ1bGUgUElVTUEgewoyMDAgKiB7eSAuMSBzIC45OTc1IHIgLS4xfSAgRUxFIHtzIC4wNH0KMTAwICoge3kgLS4xIHMgLjk5MyByIC4yfSAgRUxFIHtzIC4wNH0KfQpydWxlIEVMRSB7CkVMIHt4IDEuNiAgciA5MCB9CkVMIHt4ICAtMS42ICByIDkwIGZsaXAgMTgwIH0KfQpydWxlIEVMewpQRU57fQpFTHtzIC45OTkgciAtLjEwMyB4IC4yfQp9CnJ1bGUgRUwgMC4wMDAyNTEgewpFTHtmbGlwIDE4MH0KfQpydWxlIEVMIDAuMDAyIHsKRUwye3MgLjh9Ci8vRUwye2ZsaXAgMCBzIC44fQp9CnJ1bGUgRUwyewpQRU57fQpFTDJ7cyAuOTk5NiByIC0uMDgzODEgeCAuMn0KfQpydWxlIEVMMiAwLjAwMDI1MSB7CkVMMntmbGlwIDE4MH0KfQpydWxlIFBFTiAzIHsKUEVOTkEge2IgMX0KfQpydWxlIFBFTnsKLy9QRU5OQSB7YiAtMSB6IC0xMH0KfQpydWxlIFBFTk5BewpDSVJDTEV7YSAtLjk5IHMgMzUgYiAtMSB6IC0yfQovL0NJUkNMRXthIC0uOTk4IHMgMTAgIHogLTF9CkNJUkNMRXthIC0uN30KfSAgICAKCg==')
print a

startshape PIUMA
background { b -.8 sat 1  h -10}
rule PIUMA {
200 * {y .1 s .9975 r -.1}  ELE {s .04}
100 * {y -.1 s .993 r .2}  ELE {s .04}
}
rule ELE {
EL {x 1.6  r 90 }
EL {x  -1.6  r 90 flip 180 }
}
rule EL{
PEN{}
EL{s .999 r -.103 x .2}
}
rule EL 0.000251 {
EL{flip 180}
}
rule EL 0.002 {
EL2{s .8}
//EL2{flip 0 s .8}
}
rule EL2{
PEN{}
EL2{s .9996 r -.08381 x .2}
}
rule EL2 0.000251 {
EL2{flip 180}
}
rule PEN 3 {
PENNA {b 1}
}
rule PEN{
//PENNA {b -1 z -10}
}
rule PENNA{
CIRCLE{a -.99 s 35 b -1 z -2}
//CIRCLE{a -.998 s 10  z -1}
CIRCLE{a -.7}
}

# slightly diferent code to insert data

In [67]:
import sqlite3
import base64
sqlite3.encode = base64.encodestring
sqlite3.decode = base64.decodestring

     
#imagedata = open('myfile.jpg', "rb").read()
imagedata = \
"""
rule EL2 0.000251 {
EL2{flip 180}
}
rule PEN 3 {
PENNA {b 1}
}
rule PEN{
//PENNA {b -1 z -10}
}
rule PENNA{
CIRCLE{a -.99 s 35 b -1 z -2}
//CIRCLE{a -.998 s 10  z -1}
CIRCLE{a -.7}
}    

"""

con = sqlite3.connect("data/sqlite-01.db")
cur = con.cursor()
cur.execute('INSERT INTO python VALUES (?, ?)', (sqlite3.encode(sqlite3.Binary(imagedata)), 'base64'))
con.commit()
con.close()

In [57]:
import sqlite3
import base64
con = sqlite3.connect("data/sqlite-01.db")

con.commit()
con.close()

In [84]:
!sqlite3 data/sqlite-01.db "pragma integrity_check;"

ok

In [ ]:
## backup a database

In [85]:
!sqlite3 data/sqlite-01.db ".backup data/sqlite-01.db.bk"

# Read and Decode the Base64 data from database

In [22]:
import sqlite3
import base64
conn = sqlite3.connect('data/sqlite-01.db')
c = conn.cursor()# Never 
for row in c.execute('SELECT * FROM python ORDER BY code'):
        #print(row),"\n-----\n","\n"
    
        dat = base64.decodestring(row[0])
        print dat 
        
con.close()

rule EL2 0.000251 {
EL2{flip 180}
}
rule PEN 3 {
PENNA {b 1}
}
rule PEN{
//PENNA {b -1 z -10}
}
rule PENNA{
CIRCLE{a -.99 s 35 b -1 z -2}
//CIRCLE{a -.998 s 10  z -1}
CIRCLE{a -.7}
}



startshape PIUMA
background { b -.8 sat 1  h -10}
rule PIUMA {
200 * {y .1 s .9975 r -.1}  ELE {s .04}
100 * {y -.1 s .993 r .2}  ELE {s .04}
}
rule ELE {
EL {x 1.6  r 90 }
EL {x  -1.6  r 90 flip 180 }
}
rule EL{
PEN{}
EL{s .999 r -.103 x .2}
}
rule EL 0.000251 {
EL{flip 180}
}
rule EL 0.002 {
EL2{s .8}
//EL2{flip 0 s .8}
}
rule EL2{
PEN{}
EL2{s .9996 r -.08381 x .2}
}
rule EL2 0.000251 {
EL2{flip 180}
}
rule PEN 3 {
PENNA {b 1}
}
rule PEN{
//PENNA {b -1 z -10}
}
rule PENNA{
CIRCLE{a -.99 s 35 b -1 z -2}
//CIRCLE{a -.998 s 10  z -1}
CIRCLE{a -.7}
}

# ----- Verify your backup -----

In [16]:
import sqlite3
import base64
conn = sqlite3.connect('data/sqlite-01.db.bk')
c = conn.cursor()# Never 
for row in c.execute('SELECT * FROM python ORDER BY code'):
        #print(row),"\n-----\n","\n"
    
        dat = base64.decodestring(row[0])
        print dat 
        
conn.close()

rule EL2 0.000251 {
EL2{flip 180}
}
rule PEN 3 {
PENNA {b 1}
}
rule PEN{
//PENNA {b -1 z -10}
}
rule PENNA{
CIRCLE{a -.99 s 35 b -1 z -2}
//CIRCLE{a -.998 s 10  z -1}
CIRCLE{a -.7}
}



startshape PIUMA
background { b -.8 sat 1  h -10}
rule PIUMA {
200 * {y .1 s .9975 r -.1}  ELE {s .04}
100 * {y -.1 s .993 r .2}  ELE {s .04}
}
rule ELE {
EL {x 1.6  r 90 }
EL {x  -1.6  r 90 flip 180 }
}
rule EL{
PEN{}
EL{s .999 r -.103 x .2}
}
rule EL 0.000251 {
EL{flip 180}
}
rule EL 0.002 {
EL2{s .8}
//EL2{flip 0 s .8}
}
rule EL2{
PEN{}
EL2{s .9996 r -.08381 x .2}
}
rule EL2 0.000251 {
EL2{flip 180}
}
rule PEN 3 {
PENNA {b 1}
}
rule PEN{
//PENNA {b -1 z -10}
}
rule PENNA{
CIRCLE{a -.99 s 35 b -1 z -2}
//CIRCLE{a -.998 s 10  z -1}
CIRCLE{a -.7}
}

### -------------------------------------------------------------------------------

# LIST - first 44 characters of code ( in base64 ) and keyword

In [4]:
# Print sample code and key words
import pandas as pd
import sqlite3
# Read sqlite query results into a pandas DataFrame
# Create a SQL connection to our SQLite database
con = sqlite3.connect("data/sqlite-01.db")

df = pd.read_sql_query("SELECT * from python", con)
# verify that result of SQL query is stored in the dataframe
print(df.head())
con.close()

                                                code     keyword
0  CnN0YXJ0c2hhcGUgUElVTUEKYmFja2dyb3VuZCB7IGIgLS...  PIUMA.cfdg
1  CnJ1bGUgRUwyIDAuMDAwMjUxIHsKRUwye2ZsaXAgMTgwfQ...      base64
2  CuKIiCBtZWFucyAnKGlzKSBhbiBlbGVtZW50IG9mJwoKRm...     what is

### -------------------------------------------------------------------------------

# GOOD SEARCH

In [31]:
import sqlite3
import base64
conn = sqlite3.connect('data/sqlite-01.db')
c = conn.cursor()# Never 
#for row in c.execute('SELECT code FROM python ORDER BY code'):
#for row in c.execute("SELECT code FROM python WHERE keyword=?", ('base64',)):
for row in c.execute("SELECT code FROM python WHERE keyword=?", ('base64',)):    
    #print(row),"\n-----\n","\n"
    #c.fetchone()[0]    
    print base64.decodestring(row[0])
    #print dat 
        
conn.close()

rule EL2 0.000251 {
EL2{flip 180}
}
rule PEN 3 {
PENNA {b 1}
}
rule PEN{
//PENNA {b -1 z -10}
}
rule PENNA{
CIRCLE{a -.99 s 35 b -1 z -2}
//CIRCLE{a -.998 s 10  z -1}
CIRCLE{a -.7}
}

In [32]:
import sqlite3
import base64
conn = sqlite3.connect('data/sqlite-01.db')
c = conn.cursor()# Never 
#for row in c.execute('SELECT code FROM python ORDER BY code'):
#for row in c.execute("SELECT code FROM python WHERE keyword=?", ('base64',)):
for row in c.execute("SELECT code FROM python WHERE keyword=?", ('PIUMA.cfdg',)):    
    #print(row),"\n-----\n","\n"
    #c.fetchone()[0]    
    print base64.decodestring(row[0])
    #print dat 
        
conn.close()

startshape PIUMA
background { b -.8 sat 1  h -10}
rule PIUMA {
200 * {y .1 s .9975 r -.1}  ELE {s .04}
100 * {y -.1 s .993 r .2}  ELE {s .04}
}
rule ELE {
EL {x 1.6  r 90 }
EL {x  -1.6  r 90 flip 180 }
}
rule EL{
PEN{}
EL{s .999 r -.103 x .2}
}
rule EL 0.000251 {
EL{flip 180}
}
rule EL 0.002 {
EL2{s .8}
//EL2{flip 0 s .8}
}
rule EL2{
PEN{}
EL2{s .9996 r -.08381 x .2}
}
rule EL2 0.000251 {
EL2{flip 180}
}
rule PEN 3 {
PENNA {b 1}
}
rule PEN{
//PENNA {b -1 z -10}
}
rule PENNA{
CIRCLE{a -.99 s 35 b -1 z -2}
//CIRCLE{a -.998 s 10  z -1}
CIRCLE{a -.7}
}

# Search for a term ( LIKE )

In [37]:
import sqlite3
import base64
conn = sqlite3.connect('data/sqlite-01.db')
c = conn.cursor()# Never 
#for row in c.execute('SELECT code FROM python ORDER BY code'):
#for row in c.execute("SELECT code FROM python WHERE keyword=?", ('base64',)):
for row in c.execute("SELECT code FROM python WHERE keyword LIKE ?", ('%base6%',)):    
    #print(row),"\n-----\n","\n"
    #c.fetchone()[0]    
    print base64.decodestring(row[0])
    #print dat 
        
conn.close()

rule EL2 0.000251 {
EL2{flip 180}
}
rule PEN 3 {
PENNA {b 1}
}
rule PEN{
//PENNA {b -1 z -10}
}
rule PENNA{
CIRCLE{a -.99 s 35 b -1 z -2}
//CIRCLE{a -.998 s 10  z -1}
CIRCLE{a -.7}
}

# Searching using Input

### You may use an exact searchword or to get full use of the term LIKE,
### you may search a term in this manner:
### %base6%    
### This will show base64,because it is LIKE base6

In [5]:
import sqlite3
import base64
conn = sqlite3.connect('data/sqlite-01.db')

STerm = raw_input("Keyword")

# You may use an exact searchword or to get full use of the term LIKE search a term in this manner:
# %base6%    This will show base64,because it is LIKE base6   


c = conn.cursor()# Never 
#for row in c.execute('SELECT code FROM python ORDER BY code'):
#for row in c.execute("SELECT code FROM python WHERE keyword=?", ('base64',)):
for row in c.execute("SELECT code FROM python WHERE keyword LIKE ?", (STerm,)):    
    #print(row),"\n-----\n","\n"
    #c.fetchone()[0]    
    print base64.decodestring(row[0])
    #print dat 
        
conn.close()

Keyword%what%

∈ means '(is) an element of'

For instance, 'Let a ∈ A
' means 'Let a be an element of A'

# END Sqlite

In [53]:
import sqlite3
import base64
conn = sqlite3.connect('data/sqlite-01.db')
c = conn.cursor()# Never do this -- insecure!

t = ('%base%',)
c.execute('SELECT code FROM python WHERE keyword LIKE ?', t)
print(c.fetchone())

(u'CnJ1bGUgRUwyIDAuMDAwMjUxIHsKRUwye2ZsaXAgMTgwfQp9CnJ1bGUgUEVOIDMgewpQRU5OQSB7\nYiAxfQp9CnJ1bGUgUEVOewovL1BFTk5BIHtiIC0xIHogLTEwfQp9CnJ1bGUgUEVOTkF7CkNJUkNM\nRXthIC0uOTkgcyAzNSBiIC0xIHogLTJ9Ci8vQ0lSQ0xFe2EgLS45OTggcyAxMCAgeiAtMX0KQ0lS\nQ0xFe2EgLS43fQp9ICAgIAoK\n',)

In [6]:
# Experimental Stuff base 64 not decoded
import sqlite3
conn = sqlite3.connect('data/sqlite-01.db')
c = conn.cursor()# Never 
for row in c.execute('SELECT * FROM python ORDER BY code'):
        #print(row),"\n-----\n","\n"
        
        print row[0],"\n",row[1],"\n-----\n",

CnJ1bGUgRUwyIDAuMDAwMjUxIHsKRUwye2ZsaXAgMTgwfQp9CnJ1bGUgUEVOIDMgewpQRU5OQSB7
YiAxfQp9CnJ1bGUgUEVOewovL1BFTk5BIHtiIC0xIHogLTEwfQp9CnJ1bGUgUEVOTkF7CkNJUkNM
RXthIC0uOTkgcyAzNSBiIC0xIHogLTJ9Ci8vQ0lSQ0xFe2EgLS45OTggcyAxMCAgeiAtMX0KQ0lS
Q0xFe2EgLS43fQp9ICAgIAoK

base64
-----
CnN0YXJ0c2hhcGUgUElVTUEKYmFja2dyb3VuZCB7IGIgLS44IHNhdCAxICBoIC0xMH0gCnJ1bGUgUElVTUEgewoyMDAgKiB7eSAuMSBzIC45OTc1IHIgLS4xfSAgRUxFIHtzIC4wNH0KMTAwICoge3kgLS4xIHMgLjk5MyByIC4yfSAgRUxFIHtzIC4wNH0KfQpydWxlIEVMRSB7CkVMIHt4IDEuNiAgciA5MCB9CkVMIHt4ICAtMS42ICByIDkwIGZsaXAgMTgwIH0KfQpydWxlIEVMewpQRU57fQpFTHtzIC45OTkgciAtLjEwMyB4IC4yfQp9CnJ1bGUgRUwgMC4wMDAyNTEgewpFTHtmbGlwIDE4MH0KfQpydWxlIEVMIDAuMDAyIHsKRUwye3MgLjh9Ci8vRUwye2ZsaXAgMCBzIC44fQp9CnJ1bGUgRUwyewpQRU57fQpFTDJ7cyAuOTk5NiByIC0uMDgzODEgeCAuMn0KfQpydWxlIEVMMiAwLjAwMDI1MSB7CkVMMntmbGlwIDE4MH0KfQpydWxlIFBFTiAzIHsKUEVOTkEge2IgMX0KfQpydWxlIFBFTnsKLy9QRU5OQSB7YiAtMSB6IC0xMH0KfQpydWxlIFBFTk5BewpDSVJDTEV7YSAtLjk5IHMgMzUgYiAtMSB6IC0yfQovL0NJUkNMRXthIC0uOTk4IHMgMTAgIHogLTF9CkNJUkNMRXthIC0uN30KfSAgICAKCg==
PIUMA.cfdg
-----
CuKIiCBtZWFucyAnKGlzKSBhbiBlbGVtZW50IG9mJwoKRm9yIGluc3RhbmNlLCAnTGV0IGEg4oiIIEEKJyBtZWFucyAnTGV0IGEgYmUgYW4gZWxlbWVudCBvZiBBJwo=
what is
-----

# Inserting data from input --- WORKING FINE

In [57]:
#experimental stuff 1
import sqlite3
conn = sqlite3.connect('data/main.db')

c = conn.cursor()

# Create table
#c.execute('''DROP TABLE IF EXISTS Products)
#             CREATE TABLE Products
#             (CatID VARCHAR(500), Name VARCHAR(500), Qty real, Price real)
#             ''')

c.execute("""CREATE TABLE Products (
             contact_id integer PRIMARY KEY,
             CatID text NOT NULL,
             description text NOT NULL,
             keywords text NOT NULL);
          """)



conn.commit()
conn.close()

In [58]:
#experimental stuff 2
import sqlite3
def insert_product(product):
    with sqlite3.connect("/home/jack/Desktop/main.db") as db:
        cursor = db.cursor()
        sql = "insert into Products (CatID,description,keywords) values (?, ?, ?)"
        cursor.execute(sql, product)
        db.commit()

if __name__ == "__main__":
    ID= int(input("enter the CatID of the product:>> "))
    Des = input("Enter description: >>")
    Keywords = int(input("Enter keywords: >>"))
    product = (ID,Des,Keywords)
    insert_product(product)

enter the CatID of the product:>> 21
Enter description: >>we

NameError: name 'we' is not defined

# Inserting data from input --- 
# WORKING FINE -- END -- verified working

# Python - - - MySQL info and CRUD code.

In [ ]:
/etc/mysql/mysql.conf.d/mysqld.cnf

In [75]:
import MySQLdb
help(MySQLdb)

Help on package MySQLdb:

NAME
    MySQLdb - MySQLdb - A DB API v2.0 compatible interface to MySQL.

FILE
    /home/jack/anaconda2/lib/python2.7/site-packages/MySQLdb/__init__.py

DESCRIPTION
    This package is a wrapper around _mysql, which mostly implements the
    MySQL C API.

    connect() -- connects to server

    See the C API specification and the MySQL documentation for more info
    on other items.

    For information on how MySQLdb handles type conversion, see the
    MySQLdb.converters module.

PACKAGE CONTENTS
    connections
    constants (package)
    converters
    cursors
    release
    times

SUBMODULES
    FIELD_TYPE

CLASSES
    __builtin__.frozenset(__builtin__.object)
        DBAPISet
    __builtin__.object
        datetime.date
            datetime.datetime
        datetime.time
    exceptions.StandardError(exceptions.Exception)
        _mysql_exceptions.MySQLError
            _mysql_exceptions.Error
                _mysql_exceptions.DatabaseError
                    _mysql_exceptions.DataError
                    _mysql_exceptions.IntegrityError
                    _mysql_exceptions.InternalError
                    _mysql_exceptions.NotSupportedError
                    _mysql_exceptions.OperationalError
                    _mysql_exceptions.ProgrammingError
                _mysql_exceptions.InterfaceError
            _mysql_exceptions.Warning(exceptions.Warning, _mysql_exceptions.MySQLError)
    exceptions.Warning(exceptions.Exception)
        _mysql_exceptions.Warning(exceptions.Warning, _mysql_exceptions.MySQLError)

    class DBAPISet(__builtin__.frozenset)
     |  A special type of set for which A == x is true if A is a
     |  DBAPISet and x is a member of that set.
     |
     |  Method resolution order:
     |      DBAPISet
     |      __builtin__.frozenset
     |      __builtin__.object
     |
     |  Methods defined here:
     |
     |  __eq__(self, other)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from __builtin__.frozenset:
     |
     |  __and__(...)
     |      x.__and__(y) <==> x&y
     |
     |  __cmp__(...)
     |      x.__cmp__(y) <==> cmp(x,y)
     |
     |  __contains__(...)
     |      x.__contains__(y) <==> y in x.
     |
     |  __ge__(...)
     |      x.__ge__(y) <==> x>=y
     |
     |  __getattribute__(...)
     |      x.__getattribute__('name') <==> x.name
     |
     |  __gt__(...)
     |      x.__gt__(y) <==> x>y
     |
     |  __hash__(...)
     |      x.__hash__() <==> hash(x)
     |
     |  __iter__(...)
     |      x.__iter__() <==> iter(x)
     |
     |  __le__(...)
     |      x.__le__(y) <==> x<=y
     |
     |  __len__(...)
     |      x.__len__() <==> len(x)
     |
     |  __lt__(...)
     |      x.__lt__(y) <==> x<y
     |
     |  __ne__(...)
     |      x.__ne__(y) <==> x!=y
     |
     |  __or__(...)
     |      x.__or__(y) <==> x|y
     |
     |  __rand__(...)
     |      x.__rand__(y) <==> y&x
     |
     |  __reduce__(...)
     |      Return state information for pickling.
     |
     |  __repr__(...)
     |      x.__repr__() <==> repr(x)
     |
     |  __ror__(...)
     |      x.__ror__(y) <==> y|x
     |
     |  __rsub__(...)
     |      x.__rsub__(y) <==> y-x
     |
     |  __rxor__(...)
     |      x.__rxor__(y) <==> y^x
     |
     |  __sizeof__(...)
     |      S.__sizeof__() -> size of S in memory, in bytes
     |
     |  __sub__(...)
     |      x.__sub__(y) <==> x-y
     |
     |  __xor__(...)
     |      x.__xor__(y) <==> x^y
     |
     |  copy(...)
     |      Return a shallow copy of a set.
     |
     |  difference(...)
     |      Return the difference of two or more sets as a new set.
     |
     |      (i.e. all elements that are in this set but not the others.)
     |
     |  intersection(...)
     |      Return the intersection of two or more sets as a new set.
     |
     |      (i.e. elements that are common to all of the sets.)
     |
     |  isdisjoint(...)
     |      Return True if two sets have a null intersection.
     |
     |  issubset(...)
     |      Report whether another set contains this set.
     |
     |  issuperset(...)
     |      Report whether this set contains another set.
     |
     |  symmetric_difference(...)
     |      Return the symmetric difference of two sets as a new set.
     |
     |      (i.e. all elements that are in exactly one of the sets.)
     |
     |  union(...)
     |      Return the union of sets as a new set.
     |
     |      (i.e. all elements that are in either set.)
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from __builtin__.frozenset:
     |
     |  __new__ = <built-in method __new__ of type object>
     |      T.__new__(S, ...) -> a new object with type S, a subtype of T

    class DataError(DatabaseError)
     |  Exception raised for errors that are due to problems with the
     |  processed data like division by zero, numeric value out of range,
     |  etc.
     |
     |  Method resolution order:
     |      DataError
     |      DatabaseError
     |      Error
     |      MySQLError
     |      exceptions.StandardError
     |      exceptions.Exception
     |      exceptions.BaseException
     |      __builtin__.object
     |
     |  Data descriptors inherited from MySQLError:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.StandardError:
     |
     |  __init__(...)
     |      x.__init__(...) initializes x; see help(type(x)) for signature
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from exceptions.StandardError:
     |
     |  __new__ = <built-in method __new__ of type object>
     |      T.__new__(S, ...) -> a new object with type S, a subtype of T
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.BaseException:
     |
     |  __delattr__(...)
     |      x.__delattr__('name') <==> del x.name
     |
     |  __getattribute__(...)
     |      x.__getattribute__('name') <==> x.name
     |
     |  __getitem__(...)
     |      x.__getitem__(y) <==> x[y]
     |
     |  __getslice__(...)
     |      x.__getslice__(i, j) <==> x[i:j]
     |
     |      Use of negative indices is not supported.
     |
     |  __reduce__(...)
     |
     |  __repr__(...)
     |      x.__repr__() <==> repr(x)
     |
     |  __setattr__(...)
     |      x.__setattr__('name', value) <==> x.name = value
     |
     |  __setstate__(...)
     |
     |  __str__(...)
     |      x.__str__() <==> str(x)
     |
     |  __unicode__(...)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from exceptions.BaseException:
     |
     |  __dict__
     |
     |  args
     |
     |  message

    class DatabaseError(Error)
     |  Exception raised for errors that are related to the
     |  database.
     |
     |  Method resolution order:
     |      DatabaseError
     |      Error
     |      MySQLError
     |      exceptions.StandardError
     |      exceptions.Exception
     |      exceptions.BaseException
     |      __builtin__.object
     |
     |  Data descriptors inherited from MySQLError:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.StandardError:
     |
     |  __init__(...)
     |      x.__init__(...) initializes x; see help(type(x)) for signature
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from exceptions.StandardError:
     |
     |  __new__ = <built-in method __new__ of type object>
     |      T.__new__(S, ...) -> a new object with type S, a subtype of T
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.BaseException:
     |
     |  __delattr__(...)
     |      x.__delattr__('name') <==> del x.name
     |
     |  __getattribute__(...)
     |      x.__getattribute__('name') <==> x.name
     |
     |  __getitem__(...)
     |      x.__getitem__(y) <==> x[y]
     |
     |  __getslice__(...)
     |      x.__getslice__(i, j) <==> x[i:j]
     |
     |      Use of negative indices is not supported.
     |
     |  __reduce__(...)
     |
     |  __repr__(...)
     |      x.__repr__() <==> repr(x)
     |
     |  __setattr__(...)
     |      x.__setattr__('name', value) <==> x.name = value
     |
     |  __setstate__(...)
     |
     |  __str__(...)
     |      x.__str__() <==> str(x)
     |
     |  __unicode__(...)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from exceptions.BaseException:
     |
     |  __dict__
     |
     |  args
     |
     |  message

    Date = class date(__builtin__.object)
     |  date(year, month, day) --> date object
     |
     |  Methods defined here:
     |
     |  __add__(...)
     |      x.__add__(y) <==> x+y
     |
     |  __eq__(...)
     |      x.__eq__(y) <==> x==y
     |
     |  __format__(...)
     |      Formats self with strftime.
     |
     |  __ge__(...)
     |      x.__ge__(y) <==> x>=y
     |
     |  __getattribute__(...)
     |      x.__getattribute__('name') <==> x.name
     |
     |  __gt__(...)
     |      x.__gt__(y) <==> x>y
     |
     |  __hash__(...)
     |      x.__hash__() <==> hash(x)
     |
     |  __le__(...)
     |      x.__le__(y) <==> x<=y
     |
     |  __lt__(...)
     |      x.__lt__(y) <==> x<y
     |
     |  __ne__(...)
     |      x.__ne__(y) <==> x!=y
     |
     |  __radd__(...)
     |      x.__radd__(y) <==> y+x
     |
     |  __reduce__(...)
     |      __reduce__() -> (cls, state)
     |
     |  __repr__(...)
     |      x.__repr__() <==> repr(x)
     |
     |  __rsub__(...)
     |      x.__rsub__(y) <==> y-x
     |
     |  __str__(...)
     |      x.__str__() <==> str(x)
     |
     |  __sub__(...)
     |      x.__sub__(y) <==> x-y
     |
     |  ctime(...)
     |      Return ctime() style string.
     |
     |  fromordinal(...)
     |      int -> date corresponding to a proleptic Gregorian ordinal.
     |
     |  fromtimestamp(...)
     |      timestamp -> local date from a POSIX timestamp (like time.time()).
     |
     |  isocalendar(...)
     |      Return a 3-tuple containing ISO year, week number, and weekday.
     |
     |  isoformat(...)
     |      Return string in ISO 8601 format, YYYY-MM-DD.
     |
     |  isoweekday(...)
     |      Return the day of the week represented by the date.
     |      Monday == 1 ... Sunday == 7
     |
     |  replace(...)
     |      Return date with new specified fields.
     |
     |  strftime(...)
     |      format -> strftime() style string.
     |
     |  timetuple(...)
     |      Return time tuple, compatible with time.localtime().
     |
     |  today(...)
     |      Current date or datetime:  same as self.__class__.fromtimestamp(time.time()).
     |
     |  toordinal(...)
     |      Return proleptic Gregorian ordinal.  January 1 of year 1 is day 1.
     |
     |  weekday(...)
     |      Return the day of the week represented by the date.
     |      Monday == 0 ... Sunday == 6
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  day
     |
     |  month
     |
     |  year
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  __new__ = <built-in method __new__ of type object>
     |      T.__new__(S, ...) -> a new object with type S, a subtype of T
     |
     |  max = datetime.date(9999, 12, 31)
     |
     |  min = datetime.date(1, 1, 1)
     |
     |  resolution = datetime.timedelta(1)

    class Error(MySQLError)
     |  Exception that is the base class of all other error exceptions
     |  (not Warning).
     |
     |  Method resolution order:
     |      Error
     |      MySQLError
     |      exceptions.StandardError
     |      exceptions.Exception
     |      exceptions.BaseException
     |      __builtin__.object
     |
     |  Data descriptors inherited from MySQLError:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.StandardError:
     |
     |  __init__(...)
     |      x.__init__(...) initializes x; see help(type(x)) for signature
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from exceptions.StandardError:
     |
     |  __new__ = <built-in method __new__ of type object>
     |      T.__new__(S, ...) -> a new object with type S, a subtype of T
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.BaseException:
     |
     |  __delattr__(...)
     |      x.__delattr__('name') <==> del x.name
     |
     |  __getattribute__(...)
     |      x.__getattribute__('name') <==> x.name
     |
     |  __getitem__(...)
     |      x.__getitem__(y) <==> x[y]
     |
     |  __getslice__(...)
     |      x.__getslice__(i, j) <==> x[i:j]
     |
     |      Use of negative indices is not supported.
     |
     |  __reduce__(...)
     |
     |  __repr__(...)
     |      x.__repr__() <==> repr(x)
     |
     |  __setattr__(...)
     |      x.__setattr__('name', value) <==> x.name = value
     |
     |  __setstate__(...)
     |
     |  __str__(...)
     |      x.__str__() <==> str(x)
     |
     |  __unicode__(...)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from exceptions.BaseException:
     |
     |  __dict__
     |
     |  args
     |
     |  message

    class IntegrityError(DatabaseError)
     |  Exception raised when the relational integrity of the database
     |  is affected, e.g. a foreign key check fails, duplicate key,
     |  etc.
     |
     |  Method resolution order:
     |      IntegrityError
     |      DatabaseError
     |      Error
     |      MySQLError
     |      exceptions.StandardError
     |      exceptions.Exception
     |      exceptions.BaseException
     |      __builtin__.object
     |
     |  Data descriptors inherited from MySQLError:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.StandardError:
     |
     |  __init__(...)
     |      x.__init__(...) initializes x; see help(type(x)) for signature
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from exceptions.StandardError:
     |
     |  __new__ = <built-in method __new__ of type object>
     |      T.__new__(S, ...) -> a new object with type S, a subtype of T
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.BaseException:
     |
     |  __delattr__(...)
     |      x.__delattr__('name') <==> del x.name
     |
     |  __getattribute__(...)
     |      x.__getattribute__('name') <==> x.name
     |
     |  __getitem__(...)
     |      x.__getitem__(y) <==> x[y]
     |
     |  __getslice__(...)
     |      x.__getslice__(i, j) <==> x[i:j]
     |
     |      Use of negative indices is not supported.
     |
     |  __reduce__(...)
     |
     |  __repr__(...)
     |      x.__repr__() <==> repr(x)
     |
     |  __setattr__(...)
     |      x.__setattr__('name', value) <==> x.name = value
     |
     |  __setstate__(...)
     |
     |  __str__(...)
     |      x.__str__() <==> str(x)
     |
     |  __unicode__(...)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from exceptions.BaseException:
     |
     |  __dict__
     |
     |  args
     |
     |  message

    class InterfaceError(Error)
     |  Exception raised for errors that are related to the database
     |  interface rather than the database itself.
     |
     |  Method resolution order:
     |      InterfaceError
     |      Error
     |      MySQLError
     |      exceptions.StandardError
     |      exceptions.Exception
     |      exceptions.BaseException
     |      __builtin__.object
     |
     |  Data descriptors inherited from MySQLError:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.StandardError:
     |
     |  __init__(...)
     |      x.__init__(...) initializes x; see help(type(x)) for signature
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from exceptions.StandardError:
     |
     |  __new__ = <built-in method __new__ of type object>
     |      T.__new__(S, ...) -> a new object with type S, a subtype of T
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.BaseException:
     |
     |  __delattr__(...)
     |      x.__delattr__('name') <==> del x.name
     |
     |  __getattribute__(...)
     |      x.__getattribute__('name') <==> x.name
     |
     |  __getitem__(...)
     |      x.__getitem__(y) <==> x[y]
     |
     |  __getslice__(...)
     |      x.__getslice__(i, j) <==> x[i:j]
     |
     |      Use of negative indices is not supported.
     |
     |  __reduce__(...)
     |
     |  __repr__(...)
     |      x.__repr__() <==> repr(x)
     |
     |  __setattr__(...)
     |      x.__setattr__('name', value) <==> x.name = value
     |
     |  __setstate__(...)
     |
     |  __str__(...)
     |      x.__str__() <==> str(x)
     |
     |  __unicode__(...)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from exceptions.BaseException:
     |
     |  __dict__
     |
     |  args
     |
     |  message

    class InternalError(DatabaseError)
     |  Exception raised when the database encounters an internal
     |  error, e.g. the cursor is not valid anymore, the transaction is
     |  out of sync, etc.
     |
     |  Method resolution order:
     |      InternalError
     |      DatabaseError
     |      Error
     |      MySQLError
     |      exceptions.StandardError
     |      exceptions.Exception
     |      exceptions.BaseException
     |      __builtin__.object
     |
     |  Data descriptors inherited from MySQLError:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from exceptions.StandardError:
     |
     |  __init__(...)
     |      x.__init__(...) initializes x; see help(type(x)) for signature
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from exceptions.StandardError:
     |
     |  __new__ = <built-in method __new__ of type object>

# WORKS WELL ----- start

In [77]:
#Works
import MySQLdb as db
con = db.connect("localhost","root","ThinkPadT$#")
cur = con.cursor()
cur.execute('CREATE DATABASE testdb3;')

1L

In [79]:
import MySQLdb as db
con = db.connect("localhost","root","ThinkPadT$#", "testdb3")
with con:
    cur = con.cursor()
    cur.execute("DROP TABLE IF EXISTS Writers")
    cur.execute("CREATE TABLE Writers(Id INT PRIMARY KEY AUTO_INCREMENT, \
                 Name VARCHAR(500))")
    cur.execute("INSERT INTO Writers(Name) VALUES('Jack Northrup')")
    cur.execute("INSERT INTO Writers(Name) VALUES('Henry Wadjob')")
    cur.execute("INSERT INTO Writers(Name) VALUES('Klepto Manic')")
    cur.execute("INSERT INTO Writers(Name) VALUES('Emila gray')")
    cur.execute("INSERT INTO Writers(Name) VALUES('Mike Stupoff')")

/home/jack/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:5: Warning: Unknown table 'testdb3.Writers'

# Insert Data Into MySql as Base64

### Base64 retains all characters and spacing formats

In [80]:
# works 
import MySQLdb as db
import json 
import base64
    
con = db.connect("localhost","root","ThinkPadT$#", "testdb5")
file = """[mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something 



#listname='mylist.json'
#stringlistvalue=json.dumps(listname)

"""
encodedlistvalue=base64.b64encode(file)
with con:
    cur = con.cursor()
    #cur.execute("DROP TABLE IF EXISTS Code")
    #cur.execute("CREATE TABLE Code(Id INT PRIMARY KEY AUTO_INCREMENT, \
    #              Name VARCHAR(500))")
    #cur.execute("INSERT INTO Code(Name) VALUES('%s')" % (encodedlistvalue))
    cur.execute("INSERT INTO Code(Name) VALUES('%s')" % (encodedlistvalue))

In [81]:
# WORKS
#!/usr/bin/python
# import the MySQLdb and sys modules
import MySQLdb
import sys
import base64
# open a database connection
# be sure to change the host IP address, username, password and database name to match your own

con = db.connect("localhost","root","ThinkPadT$#", "testdb5")

# prepare a cursor object using cursor() method
#cursor = connection.cursor ()
cur = con.cursor()

# execute the SQL query using execute() method.
cur.execute ("select Id, Name from Code")

# fetch all of the rows from the query
data = cur.fetchall ()



# print the rows
for row in data :
    encodedlistvalue=base64.b64decode(row[1])
    print row[0], encodedlistvalue

# close the cursor object
cur.close ()

# close the connection
con.close ()

# exit the program
sys.exit()

1 mylist
2 "mylist"
3 "mylist.json"
4
5 [mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something
6 [mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something
7 [mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something



#listname='mylist.json'
#stringlistvalue=json.dumps(listname)


8 [mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something



#listname='mylist.json'
#stringlistvalue=json.dumps(listname)

SystemExit:

/home/jack/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

# WORKS WELL  ----- end

# Still Working with keywords

In [128]:
#Works
import MySQLdb as db
con = db.connect("localhost","root","ThinkPadT$#")
cur = con.cursor()
cur.execute('CREATE DATABASE searchdb01;')

1L

In [137]:
# works 
import MySQLdb as db
import json 
import base64
    
con = db.connect("localhost","root","ThinkPadT$#", "searchdb01")
file = """[mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something 



#listname='mylist.json'
#stringlistvalue=json.dumps(listname)

"""
keywords = """
database, code, python, lesson 1, Oh234
"""

encodedlistvalue=base64.b64encode(file)
with con:
    cur = con.cursor()
    cur.execute("DROP TABLE IF EXISTS Code")
    cur.execute("CREATE TABLE Code(Id INT PRIMARY KEY AUTO_INCREMENT, \
                  Name VARCHAR(2500), Keywords VARCHAR(500))")
    #cur.execute("INSERT INTO Code(Name) VALUES('%s')" % (encodedlistvalue))
    cur.execute("INSERT INTO Code(Name, Keywords) VALUES('%s','%s')" % (encodedlistvalue, keywords))

# Still Working with keywords --end

In [128]:
#Works
import MySQLdb as db
con = db.connect("localhost","root","ThinkPadT$#")
cur = con.cursor()
cur.execute('CREATE DATABASE searchdb01;')

1L

In [142]:
# works 
import MySQLdb as db
import json 
import base64
    
con = db.connect("localhost","root","ThinkPadT$#", "searchdb01")
file = """
[mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something 



#listname='mylist.json'
#stringlistvalue=json.dumps(listname)

"""
keywords = """
database, code, python, lesson 1, Oh234
"""

encodedlistvalue=base64.b64encode(file)
with con:
    cur = con.cursor()
    cur.execute("DROP TABLE IF EXISTS Code")
    cur.execute("CREATE TABLE Code(Id INT PRIMARY KEY AUTO_INCREMENT, \
                  Name VARCHAR(2500), Keywords VARCHAR(500))")
    #cur.execute("INSERT INTO Code(Name) VALUES('%s')" % (encodedlistvalue))
    cur.execute("INSERT INTO Code(Name, Keywords) VALUES('%s','%s')" % (encodedlistvalue, keywords))

In [143]:
# works 
import MySQLdb as db
import json 
import base64
    
con = db.connect("localhost","root","ThinkPadT$#", "searchdb01")
file = """
URL transformed to HTTPS due to an HSTS policy
--2017-07-09 13:01:34--  https://asd.gsfc.nasa.gov/archive/hubble/Hubble_20th.jpg
Resolving asd.gsfc.nasa.gov (asd.gsfc.nasa.gov)... 129.164.179.20, 2001:4d0:2310:150::20
Connecting to asd.gsfc.nasa.gov (asd.gsfc.nasa.gov)|129.164.179.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 49600 (48K) [image/jpeg]
Saving to: ‘image.jpg’

image.jpg           100%[===================>]  48.44K   153KB/s    in 0.3s    

2017-07-09 13:01:36 (153 KB/s) - ‘image.jpg’ saved [49600/49600]

Error: near line 1: table images already exists

"""
keywords = """
Resolving, asd.gsfc, nasa.gov, rt5eg
"""

encodedlistvalue=base64.b64encode(file)
with con:
    cur = con.cursor()
    #cur.execute("DROP TABLE IF EXISTS Code")
    #cur.execute("CREATE TABLE Code(Id INT PRIMARY KEY AUTO_INCREMENT, \
    #              Name VARCHAR(500), Keywords VARCHAR(500))")
    #cur.execute("INSERT INTO Code(Name) VALUES('%s')" % (encodedlistvalue))
    cur.execute("INSERT INTO Code(Name, Keywords) VALUES('%s','%s')" % (encodedlistvalue, keywords))

In [147]:
#!/usr/bin/python
# import the MySQLdb and sys modules
import MySQLdb
import sys

# open a database connection
# be sure to change the host IP address, username, password and database name to match your own

con = db.connect("localhost","root","ThinkPadT$#", "searchdb01")

# prepare a cursor object using cursor() method
#cursor = connection.cursor ()
cur = con.cursor()

# execute the SQL query using execute() method.
cur.execute ("select Id, Name, Keywords from Code")

# fetch all of the rows from the query
data = cur.fetchall ()

# print the rows
for row in data :
    print row[0], row[1], "\n", "Keywords: ", row[2], "\n -----------------------------"

# close the cursor object
cur.close ()

# close the connection
con.close ()

# exit the program
sys.exit()

1 CltteWxpc3QuanNuCgp3aGlsZSAxOgogICAgbGluZSA9IGZpbGUucmVhZGxpbmUoKQogICAgaWYgbm90IGxpbmU6CiAgICAgICAgYnJlYWsKICAgIHBhc3MgIyBkbyBzb21ldGhpbmcgCgoKCiNsaXN0bmFtZT0nbXlsaXN0Lmpzb24nCiNzdHJpbmdsaXN0dmFsdWU9anNvbi5kdW1wcyhsaXN0bmFtZSkKCg==
Keywords:
database, code, python, lesson 1, Oh234

 -----------------------------
2 ClVSTCB0cmFuc2Zvcm1lZCB0byBIVFRQUyBkdWUgdG8gYW4gSFNUUyBwb2xpY3kKLS0yMDE3LTA3LTA5IDEzOjAxOjM0LS0gIGh0dHBzOi8vYXNkLmdzZmMubmFzYS5nb3YvYXJjaGl2ZS9odWJibGUvSHViYmxlXzIwdGguanBnClJlc29sdmluZyBhc2QuZ3NmYy5uYXNhLmdvdiAoYXNkLmdzZmMubmFzYS5nb3YpLi4uIDEyOS4xNjQuMTc5LjIwLCAyMDAxOjRkMDoyMzEwOjE1MDo6MjAKQ29ubmVjdGluZyB0byBhc2QuZ3NmYy5uYXNhLmdvdiAoYXNkLmdzZmMubmFzYS5nb3YpfDEyOS4xNjQuMTc5LjIwfDo0NDMuLi4gY29ubmVjdGVkLgpIVFRQIHJlcXVlc3Qgc2VudCwgYXdhaXRpbmcgcmVzcG9uc2UuLi4gMjAwIE9LCkxlbmd0aDogNDk2MDAgKDQ4SykgW2ltYWdlL2pwZWddClNhdmluZyB0bzog4oCYaW1hZ2UuanBn4oCZCgppbWFnZS5qcGcgICAgICAgICAgIDEwMCVbPT09PT09PT09PT09PT09PT09PT5dICA0OC40NEsgICAxNTNLQi9zICAgIGluIDAuM3MgICAgCgoyMDE3LTA3LTA5IDEzOjAxOjM2ICgxNTMgS0IvcykgLSDigJhpbWFnZS5qcGfigJkgc2F2ZWQgWzQ5NjAwLzQ5NjAwXQoKRXJyb3I6IG5lYXIgbGluZSAxOiB0YWJsZSBpbWFnZXMgYWxyZWFkeSBleGlzdHMKCg==
Keywords:
Resolving, asd.gsfc, nasa.gov, rt5eg

 -----------------------------

SystemExit:

# Decode base64 'Name' column

In [150]:
# WORKS
#!/usr/bin/python
# import the MySQLdb and sys modules
import MySQLdb
import sys
import base64
# open a database connection
# be sure to change the host IP address, username, password and database name to match your own

con = db.connect("localhost","root","ThinkPadT$#", "searchdb01")

# prepare a cursor object using cursor() method
#cursor = connection.cursor ()
cur = con.cursor()

# execute the SQL query using execute() method.
cur.execute ("select Id, Name, Keywords from Code")

# fetch all of the rows from the query
data = cur.fetchall ()



# print the rows
for row in data :
    encodedlistvalue=base64.b64decode(row[1])
    print row[0], encodedlistvalue, '\n', 'Keywords:', row[2], '\n -----------------------------\n'

# close the cursor object
cur.close ()

# close the connection
con.close ()

# exit the program
sys.exit()

1
[mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something



#listname='mylist.json'
#stringlistvalue=json.dumps(listname)


Keywords:
database, code, python, lesson 1, Oh234

 -----------------------------

2
URL transformed to HTTPS due to an HSTS policy
--2017-07-09 13:01:34--  https://asd.gsfc.nasa.gov/archive/hubble/Hubble_20th.jpg
Resolving asd.gsfc.nasa.gov (asd.gsfc.nasa.gov)... 129.164.179.20, 2001:4d0:2310:150::20
Connecting to asd.gsfc.nasa.gov (asd.gsfc.nasa.gov)|129.164.179.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 49600 (48K) [image/jpeg]
Saving to: ‘image.jpg’

image.jpg           100%[===================>]  48.44K   153KB/s    in 0.3s

2017-07-09 13:01:36 (153 KB/s) - ‘image.jpg’ saved [49600/49600]

Error: near line 1: table images already exists


Keywords:
Resolving, asd.gsfc, nasa.gov, rt5eg

 -----------------------------

SystemExit:

# Decode base64 'Name' column WORKING FINE -- Above

# WORKING  _ - _ Searching for Keywords

In [152]:
import MySQLdb
con = db.connect("localhost","root","ThinkPadT$#", "searchdb01")

#db = MySQLdb.connect (host = "localhost",
#                          user = "root",
#                          passwd = "root",
#                          db = "test")
param = "Resolving"

#par = param

c = con.cursor()

#c.execute("SELECT * FROM data WHERE params LIKE ('%s%') LIMIT 1"  % (param))
c.execute("SELECT * FROM Code WHERE Keywords LIKE %s LIMIT 1", ("%" + param + "%",))

data = c.fetchall()

# print the rows
for row in data :
    encodedlistvalue=base64.b64decode(row[1])
    print row[0], encodedlistvalue, '\n', 'Keywords:', row[2], '\n -----------------------------\n'



c.close()

2
URL transformed to HTTPS due to an HSTS policy
--2017-07-09 13:01:34--  https://asd.gsfc.nasa.gov/archive/hubble/Hubble_20th.jpg
Resolving asd.gsfc.nasa.gov (asd.gsfc.nasa.gov)... 129.164.179.20, 2001:4d0:2310:150::20
Connecting to asd.gsfc.nasa.gov (asd.gsfc.nasa.gov)|129.164.179.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 49600 (48K) [image/jpeg]
Saving to: ‘image.jpg’

image.jpg           100%[===================>]  48.44K   153KB/s    in 0.3s

2017-07-09 13:01:36 (153 KB/s) - ‘image.jpg’ saved [49600/49600]

Error: near line 1: table images already exists


Keywords:
Resolving, asd.gsfc, nasa.gov, rt5eg

 -----------------------------

In [153]:
import MySQLdb
con = db.connect("localhost","root","ThinkPadT$#", "searchdb01")

#db = MySQLdb.connect (host = "localhost",
#                          user = "root",
#                          passwd = "root",
#                          db = "test")
param = "Oh234"

#par = param

c = con.cursor()

#c.execute("SELECT * FROM data WHERE params LIKE ('%s%') LIMIT 1"  % (param))
c.execute("SELECT * FROM Code WHERE Keywords LIKE %s LIMIT 1", ("%" + param + "%",))

data = c.fetchall()

# print the rows
for row in data :
    encodedlistvalue=base64.b64decode(row[1])
    print row[0], encodedlistvalue, '\n', 'Keywords:', row[2], '\n -----------------------------\n'



c.close()

1
[mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something



#listname='mylist.json'
#stringlistvalue=json.dumps(listname)


Keywords:
database, code, python, lesson 1, Oh234

 -----------------------------

# SEARCHING BY KEYWORDS END

In [164]:
def process_file(filename):
    reg = re.compile(r'([\w]{2,3}):\s') # Matches line header
    tmp = '' # Stored/cached data for mutliline string
    key = None # Current key
    data = {}

    with open(filename,'r') as f:
        for row in f:
            row = row.rstrip()
            match = reg.match(row)

            # Matches header or is end, put string to list:
            if (match or not row) and key:
                data[key] = tmp
                key = None
                tmp = ''

            # Empty row, next dataset
            if not row:
                # Prevent empty returns
                if data:
                    yield data
                    data = {}

                continue

            # We do have header
            if match:
                key = str(match.group(1))
                tmp = row[len(match.group(0)):]
                continue

            # No header, just append string -> here goes assumption that you want to
            # remove newlines, trailing spaces and replace them with one single space
            tmp += ' ' + row

    # Missed row?
    if key:
        data[key] = tmp

    # Missed group?
    if data:
        yield data

In [168]:
data = process_file("mylist")

In [ ]:
# %load mylist
"""
python - Searching for Phrase Keywords in MySQL - Stack Overflow
https://stackoverflow.com/questions/.../searching-for-phrase-keywords-in-mysql
May 16, 2015 - 

"""

In [85]:
%%writefile mylist
"""
python - Searching for Phrase Keywords in MySQL - Stack Overflow
https://stackoverflow.com/questions/.../searching-for-phrase-keywords-in-mysql
May 16, 2015 - 

"""

Writing mylist

In [ ]:
data = %load mylist
print data

# SOME NOT WORKING EXPERIMENTS with JSON

In [83]:
# works 
import MySQLdb as db
import json 
import base64
    
con = db.connect("localhost","root","ThinkPadT$#", "searchdb01")
c = con.cursor()
#data = %load mylist
keywords = """
data, webite, cut paste, 87er
"""
encodedlistvalue=base64.b64encode('%load mylist')
# Put this through to SQL using an INSERT statement...
c.execute("""INSERT INTO Code (Name, Keywords)
                   VALUES(%s, %s)""", (encodedlistvalue, keywords))

1L

In [89]:
%%writefile mylist.jsn
[row = cursor.fetchone()
while row:
    #print(row)
    rowstring = "" # printed for each row
    result = row[b64field_idx] # set to base64 field value
    
    for j in range(numcols):
        rowstring += str(row[j]) + "\t" # Need to print each column (tab separated)
         
    try:
        # Now we can Base64 decode however many times they want
        for j in range(args.b64count) :
            temp = base64.decodestring(result)
            result = temp
        rowstring += result # Add the decoded result to the output string
        ]

Writing mylist.jsn

In [90]:
# works 
import MySQLdb as db
import json 
import base64
    
con = db.connect("localhost","root","ThinkPadT$#", "testdb5")
file = """[mylist.jsn

while 1:
    line = file.readline()
    if not line:
        break
    pass # do something 



#listname='mylist.json'
#stringlistvalue=json.dumps(listname)

"""
encodedlistvalue=base64.b64encode(file)
with con:
    cur = con.cursor()
    #cur.execute("DROP TABLE IF EXISTS Code")
    #cur.execute("CREATE TABLE Code(Id INT PRIMARY KEY AUTO_INCREMENT, \
    #              Name VARCHAR(500))")
    #cur.execute("INSERT INTO Code(Name) VALUES('%s')" % (encodedlistvalue))
    cur.execute("INSERT INTO Code(Name) VALUES('%s')" % (encodedlistvalue))

In [91]:
#!/usr/bin/python
# import the MySQLdb and sys modules
import MySQLdb
import sys

# open a database connection
# be sure to change the host IP address, username, password and database name to match your own

con = db.connect("localhost","root","ThinkPadT$#", "testdb5")

# prepare a cursor object using cursor() method
#cursor = connection.cursor ()
cur = con.cursor()

# execute the SQL query using execute() method.
cur.execute ("select Id, Name from Code")

# fetch all of the rows from the query
data = cur.fetchall ()

# print the rows
for row in data :
    print row[0], row[1]

# close the cursor object
cur.close ()

# close the connection
con.close ()

# exit the program
sys.exit()

1 bXlsaXN0
2 Im15bGlzdCI=
3 Im15bGlzdC5qc29uIg==
4
5 W215bGlzdC5qc24KCndoaWxlIDE6CiAgICBsaW5lID0gZmlsZS5yZWFkbGluZSgpCiAgICBpZiBub3QgbGluZToKICAgICAgICBicmVhawogICAgcGFzcyAjIGRvIHNvbWV0aGluZyA=
6 W215bGlzdC5qc24KCndoaWxlIDE6CiAgICBsaW5lID0gZmlsZS5yZWFkbGluZSgpCiAgICBpZiBub3QgbGluZToKICAgICAgICBicmVhawogICAgcGFzcyAjIGRvIHNvbWV0aGluZyA=
7 W215bGlzdC5qc24KCndoaWxlIDE6CiAgICBsaW5lID0gZmlsZS5yZWFkbGluZSgpCiAgICBpZiBub3QgbGluZToKICAgICAgICBicmVhawogICAgcGFzcyAjIGRvIHNvbWV0aGluZyAKCgoKI2xpc3RuYW1lPSdteWxpc3QuanNvbicKI3N0cmluZ2xpc3R2YWx1ZT1qc29uLmR1bXBzKGxpc3RuYW1lKQoK
8 W215bGlzdC5qc24KCndoaWxlIDE6CiAgICBsaW5lID0gZmlsZS5yZWFkbGluZSgpCiAgICBpZiBub3QgbGluZToKICAgICAgICBicmVhawogICAgcGFzcyAjIGRvIHNvbWV0aGluZyAKCgoKI2xpc3RuYW1lPSdteWxpc3QuanNvbicKI3N0cmluZ2xpc3R2YWx1ZT1qc29uLmR1bXBzKGxpc3RuYW1lKQoK
9 W215bGlzdC5qc24KCndoaWxlIDE6CiAgICBsaW5lID0gZmlsZS5yZWFkbGluZSgpCiAgICBpZiBub3QgbGluZToKICAgICAgICBicmVhawogICAgcGFzcyAjIGRvIHNvbWV0aGluZyAKCgoKI2xpc3RuYW1lPSdteWxpc3QuanNvbicKI3N0cmluZ2xpc3R2YWx1ZT1qc29uLmR1bXBzKGxpc3RuYW1lKQoK

SystemExit:

In [93]:
# works 
import MySQLdb as db
import json 
import base64
    
con = db.connect("localhost","root","ThinkPadT$#", "testdb5")

with con:
    cur = con.cursor()

#for row in cur.execute('select * from Code limit 150'):
#    print(row)

row = cur.execute('select * from Code WHERE Id=6')
print(row)

        #cur.execute("INSERT INTO Code(Name) VALUES('%s')" % (encodedlistvalue))
        # cur.execute("INSERT INTO Code(Name) VALUES('%s')" % (encodedlistvalue))

1

In [103]:

#And a raw, simple example
import pymysql
import json 
import base64
      
listname='mylist'
dbhost="127.0.0.1"
#dbhost="mysql"
dbuser="root"
dbpwd="ThinkPadT$#"
dbdatabase="testdb3"
    
# serialize list into a string, and then encode in SQL-safe base64 format 
stringlistvalue=json.dumps('mylist')
encodedlistvalue=base64.b64encode(stringlistvalue)

db = pymysql.connect(dbhost,dbuser,dbpwd,dbdatabase )
     
# Prepare SQL query to INSERT a record into the database.
#sql = "INSERT INTO Writers(listname, listvalue) VALUES ('%s', '%s')" % (listname, encodedlistvalue)
sql = "INSERT INTO Writers(Name) VALUES ('%s')" % (encodedlistvalue)
try:
    # Execute the SQL command
    cursor.execute(sql)
    # Commit your changes in the database
    db.commit()
except:
    # Rollback in case there is any error
    db.rollback()
finally:
    # disconnect from server
    db.close()

In [ ]:
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('ThinkPadT$#');

To change password:
sudo dpkg-reconfigure mysql-server-5.5

In [ ]:
sudo mysql -u root
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('ThinkPadT$#');
CREATE USER 'jack'@'localhost' IDENTIFIED BY 'ThinkPadT$#';
GRANT ALL PRIVILEGES ON * . * TO 'jack'@'localhost';
FLUSH PRIVILEGES;

# Function to create database - START

In [5]:
def createdb(sqlitedbase):
    import sqlite3
    conn = sqlite3.connect(sqlitedbase)
    c = conn.cursor()
  
    query1 = "DROP TABLE IF EXISTS Junk"
    query2 = """CREATE TABLE IF NOT EXISTS Junk(
    "language" VARCHAR(32) NOT NULL,
    "keywords" VARCHAR(500) default NULL,
    "script" VARCHAR(2500) default NULL
    )
    """
    c.execute(query1)
    c.execute(query2)

In [6]:
createdb("newdatabase02")

In [8]:
import sqlite3
conn = sqlite3.connect('newdatabase02')

c = conn.cursor()
c.execute("INSERT INTO Junk VALUES ('SQLite','Junkstuff, stuff, sql','beans')")  
conn.commit()

conn.close()

In [14]:
import sqlite3
conn = sqlite3.connect('newdatabase02')

c = conn.cursor()
s = ('stuff',)
#c.execute('SELECT * FROM Junk WHERE keywords=?', s)
c.execute('SELECT * FROM Junk')
#print(c.fetchmany())
print(c.fetchall())

[(u'SQLite', u'Junkstuff, stuff, sql', u'beans'), (u'SQLlite', u'computer stuff, sqlite, iu5t', u'c3RyaW5nbGlzdHZhbHVl')]

In [12]:
import sqlite3
import base64
conn = sqlite3.connect('newdatabase02')

stringlistvalue ="""
this is a test
"""
c = conn.cursor()
# Insert a row of data
encodedlistvalue=base64.b64encode('stringlistvalue')
language ="SQLlite"
keywords ="computer stuff, sqlite, iu5t"
#c.execute  "INSERT INTO Junk VALUES ('Python','Python, script, sql', '%s')" % (encodedlistvalue)
#  "INSERT INTO Junk VALUES ('Python','Python, script, sql', '%s')" % (encodedlistvalue)
    
#c.execute("INSERT INTO Junk VALUES (?,?,?);", (encodedlistvalue)  


c.execute("INSERT INTO Junk VALUES (?, ?, ?);", (language, keywords, encodedlistvalue))


#c.execute(query1) 
#sql = "INSERT INTO Writers(Name) VALUES ('%s')" % (encodedlistvalue)


#3db = pymysql.connect(dbhost,dbuser,dbpwd,dbdatabase )
     
# Prepare SQL query to INSERT a record into the database.
#sql = "INSERT INTO Writers(listname, listvalue) VALUES ('%s', '%s')" % (listname, encodedlistvalue)
#sql = "INSERT INTO Writers(Name) VALUES ('%s')" % (encodedlistvalue)
#3try:
    # Execute the SQL command
 #   cursor.execute(sql)
    # Commit your changes in the database
#    db.commit()

# Save (commit) the changes
conn.commit()

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.
conn.close()

# Function to create database TESTED - END

In [8]:
import sqlite3
conn = sqlite3.connect('newdatabase02')

stringlistvalue ="""
this is a test
"""
c = conn.cursor()
# Insert a row of data
#encodedlistvalue=base64.b64encode(stringlistvalue)
#c.execute  "INSERT INTO Junk VALUES ('Python','Python, script, sql', '%s')" % (encodedlistvalue)
#  "INSERT INTO Junk VALUES ('Python','Python, script, sql', '%s')" % (encodedlistvalue)
    
c.execute("INSERT INTO Junk VALUES ('SQLite','Junkstuff, stuff, sql','beans')")  
    
#c.execute(query1) 
#sql = "INSERT INTO Writers(Name) VALUES ('%s')" % (encodedlistvalue)


#3db = pymysql.connect(dbhost,dbuser,dbpwd,dbdatabase )
     
# Prepare SQL query to INSERT a record into the database.
#sql = "INSERT INTO Writers(listname, listvalue) VALUES ('%s', '%s')" % (listname, encodedlistvalue)
#sql = "INSERT INTO Writers(Name) VALUES ('%s')" % (encodedlistvalue)
#3try:
    # Execute the SQL command
 #   cursor.execute(sql)
    # Commit your changes in the database
#    db.commit()

# Save (commit) the changes
conn.commit()

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.
conn.close()

In [ ]:
# Larger example that inserts many records at a time
purchases = [('2006-03-28', 'BUY', 'IBM', 1000, 45.00),
             ('2006-04-05', 'BUY', 'MSFT', 1000, 72.00),
             ('2006-04-06', 'SELL', 'IBM', 500, 53.00),
            ]
c.executemany('INSERT INTO python VALUES (?,?,?,?,?)', purchases)